apiVersion: v1
kind: Service
metadata:
  name: consumer-three-service
  namespace: my-namespace
spec:
  selector:
    app: consumer-three
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
