apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: Kompose_StatefulSet
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  clusterIP: None
  selector:
    io.kompose.service: mysql-db
