apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: bharathoptdocker/python-producer:1
          ports:
            - containerPort: 5000
